defaults:
  - model: vae
  - trainer: default
  - logger: wandb
  - data: mvtec
  - loss: l1
  - experiments: matrix
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

seed: 42
experiment_name: ${model.name}_${loss.name}
